name: Create release

on:
    push:
        tags:
            - "v*"

jobs:
    build-and-release:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Clean stale artifacts
              run: git clean -dfx

            - name: Setup python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - name: Install build
              run: |
                  python -m pip install --upgrade pip
                  pip install build

            - name: Create packages
              run: python -m build

            - name: Create release
              uses: softprops/action-gh-release@v2
              with:
                  files: dist/*
                  generate_release_notes: true
